### ISSUE TITLE
Problem to run IKOS in macOS sequoia 15.1

### ISSUE THREAD

**Issue by AlPeUAG** [NASA-SW-VnV/ikos#297] opened 2024-11-12 19:54 UTC
I install IKOS using the brew command, then when I try to analyze any code, this error appears: error could not find ikos python module, error: see TROUBLESHOOTING.md
What could be wrong, I already reinstall ikos with brew but is the same, someone can help me?

**Comment by drpaneas** [comment] 2024-11-15 14:21
Same here.

**Comment by fouzhe** [comment] 2024-11-16 14:29
Same here

**Comment by TheBjoel2** [comment] 2024-11-19 22:31
https://github.com/jupyter/nbclassic/issues/308

**Comment by ivanperez-keera** [comment] 2024-11-26 21:24
It could be a duplicate of #292. Could you try the latest version in the repo (not yet tagged) and see if that works?

**Comment by ivanperez-keera** [comment] 2024-12-10 13:43
A similar issue was reported (https://github.com/NASA-SW-VnV/ikos/issues/305) and was fixed when #292 was fixed. Reinstalling from source until the next release should address the issue.

If not, please re-open this ticket. Thanks!

**Closed as not planned by ivanperez-keera** 2024-12-10 13:43 UTC
