### ISSUE TITLE
Problem with narrowing strategy for nonmonotonic transformation function

### ISSUE THREAD

**Issue by wutianba** [NASA-SW-VnV/ikos#7] opened 2018-11-29 09:22 UTC
```c++
int count = 10;
int main() {
  int i;
  for (i = 0; i < 10; i++) {
    count = count >> 1;
  }
  return 0;
}
```
it seems having problem with narrowing strategy for nonmonotonic transformation function.
like code upon, using interval domain, the analyzer can not stop.

**Comment by arthaud** [comment] 2018-11-29 22:31
Hi @wutianba,

Thanks for reporting this issue.

I am surprised that I've never seen this before. There is indeed an issue with the decreasing iterations (narrowing) during the fixpoint computation. It does not converge for this code.

Here is approximately what happens:
* After the increasing iterations (widening), we get the interval `[INT_MIN, 10]` for `count` at the beginning of the loop;
* Then, we start the decreasing iterations. First, we use the meet abstract operator for the first iteration, and we get `[-536870912, 10]` at the beginning of the loop;
* Then, we try to converge using the narrowing on itervals, as defined in the literature. Running an iteration gives us `[-268435456, 10]` at the beginning of the loop. Since this is not a fixpoint, we apply the narrowing and get: `narrow([-536870912, 10], [-268435456, 10]) = [-536870912, 10]`. Hence, the infinite loop.

I have to review my abstract interpretation materials, as I am very puzzled at the definition of the narrowing for intervals (i.e, `narrow([L0, U0], [L1, U1]) = [if L0=-oo then L1 else L0, if U0=+oo then U1 else U0]`). I think this is not enough to assure convergence (e.g, with your code). I don't understand why the meet operator is not used instead since there is no infinite chain of decreasing intervals anyway.

**Comment by wutianba** [comment] 2018-11-30 08:33
Thanks for your repley.
I'm not sure if it's right, but in my understanding, the narrowing operation can only be used on a widened result and a boundary. I am not sure if the subsequent narrowing operation is correct.
Therefore, I have been confused, how to narrow the results after widening, I think there is no good way to find an exact boundary.
Also, if I remove all the code of narrowing, is there any problem?
Thanks again.

**Comment by arthaud** [comment] 2018-11-30 18:02
Hi again,

I talked yesterday with a coworker and it is now clear to me.

The convergence of the fixpoint is assured by the narrowing operator only if it is applied on a fixpoint after a widening. The [current implementation](https://github.com/NASA-SW-VnV/ikos/blob/66d71375bb153d1779c047ed609da2e62f9a0ad3/core/include/ikos/core/fixpoint/fwd_fixpoint_iterator.hpp#L230) does an additional step with a meet (probably to improve the precision) before the narrowing, which breaks the convergence.

The right strategy is to apply the narrowing first until it converges, and then possibly add a fixed number of steps with meets to improve the precision.

There is also another problem: we check the convergence before applying the narrowing. This is not what the literature says and it also breaks the convergence.

I will push a fix within the day.

@wutianba: You were right that the narrowing needs to be applied right after the widening.
@wutianba: You could remove the narrowing steps as a quick fix, yes, but you might lose precision.
@kokke: Thanks for you comment. Hopefully my incoming patch should fix all your issues. If not, feel free to open a new issue on Github.
@kokke: Yes, the analysis is theoretically supposed to converge for any abstract domain, given that it provides a correct widening and narrowing. From what I know, some complex abstract domains do not provide a narrowing operator, in that case we can simply skip the decreasing iterations (This is what we do for APRON abstract domains, see [interprocedural.cpp#L445](https://github.com/NASA-SW-VnV/ikos/blob/66d71375bb153d1779c047ed609da2e62f9a0ad3/analyzer/src/analysis/value/interprocedural.cpp#L445))

**Comment by kokke** [comment] 2018-11-30 18:54
Hi @arthaud thanks for the response. I am looking forward to trying out your fix.

My context is mostly GCC-based builds for ARM CPU's (Cortex-M0, M3, M4, R4). 

I also had a problem with the construct `while (1);`, used a few places as a stupid way to halt execution (the system would get reset by the hardware watchdog). I had to replace the while-loop with `assert(0)` to get convergence. I'm excited to see if that is remedied also :)

I am super impressed by IKOS. It's really fast and uses very little RAM compared to other tools :+1:

**Comment by arthaud** [comment] 2018-12-01 01:35
I fixed the errors and improved the fixpoint iterator implementation. This issue is now fixed.

I actually added an optimization: when we reach the fixpoint during the increasing iterations `new_pre.leq(pre)`, we can use the narrowing right away. This saves an iteration for each cycle, and gives exactly the same results. IKOS is now ~20% faster in average (in debug mode). This is great!

@kokke: Thanks! I am actually trying to write a report for my supervisors about the influence of IKOS in the industry. If you are using IKOS at work, I would really appreciate if you could tell me more about it! For instance: what is your company, in which context do you use IKOS, are you satisfied about the results, etc. Feel free to email us at ikos@lists.nasa.gov! Even a few lines would be really appreciated!

@kokke: I understand your issue with `while(1);`. IKOS probably tells you that the code after the loop is unreachable, which is sound wrt. the C standard. We could maybe try to add an option to ignore `while(1);`. Feel free to open an issue about it ;)

**Comment by arthaud** [comment] 2018-12-01 01:39
By the way, we will release a new version soon, including:
*  ikos-scan (a tool to replace wllvm);
* upgrade to llvm 7;
* support for Windows using msys2.

**Comment by wutianba** [comment] 2018-12-01 05:56
@arthaud 
Supporting windows is a great idea, I spent too much effort to get ikos1.3 compiled with msvc or let ikos2.0 run on windows xp. I think Cygwin-2.5.2 might be better, it might be the last version of Cygwin or msys that can compile ikos2 for window xp(32bit).

**Comment by arthaud** [comment] 2018-12-01 17:34
I will try to see if I can support Cygwin as well. I don't know if it's easy to get all the dependencies (e.g, llvm).

**Comment by kokke** [comment] 2018-12-03 10:07
Hi @arthaud - that fixed my convergence problems :) Thank you very much for the fast support.

I would be glad if I could help you. I will send an email to the IKOS-list, detailing what our company does, how we use IKOS (and static analysis in general) and what we think of IKOS compared to other tools.

**Comment by kokke** [comment] 2018-12-03 13:36
Hi @arthaud 

I was a bit too fast there - I still have problems getting analysis to converge on this function:

```C
uint32_t CLKPWR_GetCLK (uint8_t ClkType)
{
    switch(ClkType)
    {
        case CLKPWR_CLKTYPE_CPU:
            return SystemCoreClock;

        case CLKPWR_CLKTYPE_PER:
            return PeripheralClock;

        case CLKPWR_CLKTYPE_EMC:
            return EMCClock;

        case CLKPWR_CLKTYPE_USB:
            return USBClock;

        default:
            while(1); //error loop
    }
}
```

`SystemCoreClock`, `PeripheralClock`, `EMCClock` and `USBClock` are all `uint32_t`-variables.

I run IKOS like this:
`ikos --entry-points=CLKPWR_GetCLK whole_program.bc`

It seems the problem is with the `while(1);`-loop, since analysis converges immediately if I replace with `assert(0);`.

**Comment by arthaud** [comment] 2018-12-03 19:37
Thanks. I was able to reproduce it and this is a bug in the dead code checker. I will have a patch soon.

Could you create a separate issue since this is not related to the narrowing?

Thank you.

**Comment by kokke** [comment] 2018-12-03 22:07
Sorry for hijacking this issue-thread :$ I have submitted a separate issue here: https://github.com/NASA-SW-VnV/ikos/issues/9

IKOS will be run on a few million lines of our industrial code the coming days and weeks :)

**Comment by arthaud** [comment] 2018-12-03 22:43
Thank you.

I am closing this since the issue is solved.

Feel free to open issues for any other bugs or questions.

**Closed by arthaud** 2018-12-03 22:43 UTC
