### ISSUE TITLE
Failed on make check

### ISSUE THREAD

**Issue by iamwonseok** [NASA-SW-VnV/ikos#159] opened 2020-03-02 02:55 UTC
I met the below error message on make check:

30/63 Test #30: core-domain-numeric-apron-pkgrid_polyhedra_lin_congruences ...***Failed    0.00 sec

```
$ ./core/test/unit/test-core-domain-numeric-apron-pkgrid_polyhedra_lin_congruences
Running 17 test cases...
unknown location(0): fatal error: in "is_top_and_bottom": memory access violation at address: 0x00000088: no mapping at fault address
ikos/core/test/unit/domain/numeric/apron/pkgrid_polyhedra_lin_congruences.cpp(70): last checkpoint

*** 1 failure is detected in the test module "test_apron_pkgrid_polyhedra_lin_congruences"
```

Could you please let me know why and how I solve this issue?

I am attaching the version of libraries on my environment (Ubuntu-18.04) from log:
```
-- Including core
-- Found Boost: /usr/include (found version "1.65.1")
-- Found the following Boost libraries:
--   unit_test_framework
-- Found GMP: /usr/include/x86_64-linux-gnu (found version "6.1.2")
-- Found TBB: /usr/include (found suitable version "9107", minimum required is "2")
-- Found MPFR: /usr/include (found version "4.0.1")
-- Found PPL: /usr/include/x86_64-linux-gnu (found version "1.2")
-- Found APRON: /usr/include
...
-- Including ar
-- Found Boost: /usr/include (found version "1.65.1")
-- Including frontend/llvm
-- Found Boost: /usr/include (found version "1.65.1")
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found LLVM: /usr/lib/llvm-9 (found version "9.0.0")
```

**Comment by arthaud** [comment] 2020-03-02 03:03
Hi @iamwonseok,

This is a duplicate of #78. Feel free to comment on the issue if you have any question.

**Closed by arthaud** 2020-03-02 03:03 UTC
