### ISSUE TITLE
Nothing to analyze - after building scons project

### ISSUE THREAD

**Issue by qarmin** [NASA-SW-VnV/ikos#142] opened 2019-07-12 15:38 UTC
Repo : https://github.com/godotengine/godot
Building instructions: https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_x11.html

I compiled ikos from master

when I try to use this command
```
ikos-scan scons p=x11 -j6
```
only this message appear:
```
Nothing to analyze.
```

**Comment by arthaud** [comment] 2019-07-12 18:58
Hi @qarmin,

`ikos-scan` works by setting the environment variables `CC`, `CXX` and `LD`. It looks like `scons` does not support these variables.

I believe you could make it work by manually editing `platform/x11/detect.py` in Godot and adding:
```python
env["CC"] = "ikos-scan-cc"
env["CXX"] = "ikos-scan-c++"
env["LINK"] = "ikos-scan-cc"
```

As a side note, I doubt you will get anything useful by running IKOS on Godot. Godot is a huge project with millions of lines of C++. IKOS was designed to analyze safety critical software written in C. It uses a mathematical theory called Abstract Interpretation to compute an over-approximation of all the reachable states. It performs whole program analysis in a context sensitive way. The analysis of millions of lines could take hours or days. It is also known that IKOS has issues with C++, see #88.

**Comment by arthaud** [comment] 2019-07-25 23:15
Any news about this? Can I close the issue?

**Closed** 2019-08-07 18:48 UTC
Labels: A-ikos-scan, C-bug, L-c++
