### ISSUE TITLE
Release notes are outdated

### ISSUE THREAD

**Issue by ivanperez-keera** [NASA-SW-VnV/ikos#219] opened 2023-07-25 15:32 UTC
The release notes are outdated. The top headline is IKOS 3.0, not 3.1.

I'd vote for using github's release feature for release notes, and removing [this file](https://github.com/NASA-SW-VnV/ikos/blob/master/RELEASE_NOTES.md) altogether. We can attach those notes to the release as a description.

**Comment by ivanperez-keera** [comment] 2023-07-25 15:34
On that note, something I've been doing for other projects and I propose for IKOS is:

- Every PR has to have an issue.
- Every change is processed via a PR.
- Every commit mentions the issue it addresses.
- Every PR is merged with `--no-ff` and closes the issue with a `Close #<IssueNumber>` in the summary line.
- Every issue has a milestone when it was addressed.

That makes it trivial to list the changes that go into a particular release.

**Comment by ivanperez-keera** [comment] 2023-07-25 17:38
I'd appreciate your input on this @arthaud . Do all of these seem sensible and easy enough to follow?

**Comment by arthaud** [comment] 2023-07-26 09:16
> The release notes are outdated. The top headline is IKOS 3.0, not 3.1.

Right, that's probably my mistake. It can be easily fixed though.

> I'd vote for using github's release feature for release notes, and removing [this file](https://github.com/NASA-SW-VnV/ikos/blob/master/RELEASE_NOTES.md) altogether. We can attach those notes to the release as a description.

Sure. In that case, should we backport all previous release notes in Github?

> Every PR has to have an issue (all changes are documented in issues)

In general I'm fine with that but that might feel a bit silly/inefficient for small PR (quick fixes, typos, etc.).

> Every change is processed via a PR (aka no direct commits to master).
Every PR is merged with --no-ff and closes the issue with a Close #<IssueNumber> in the summary line.

I guess that makes sense. In the past, we mostly worked on the internal NASA repository but we can now make Github the source of truth (it already is). These guidelines make sense and seem healthy for an open source setup.

> Every commit mentions the issue it addresses (we can use one of (#<Issue number>), [#<Issue number>] or Refs #<Issue number> in the summary line).

cf previous comment, that could seem a bit silly for very small changes. Otherwise LGTM.

> Every issue has a milestone when it will be or was addressed.

I don't think that's possible. We have plenty of issues opened by users with bugs we can't reproduce (e.g, #29), things we know are really hard to fix (#196) or just ideas we might not have time to explore (#211). I wouldn't put arbitrary milestones on all of those.

**Comment by ivanperez-keera** [comment] 2023-07-26 14:35
>  In that case, should we backport all previous release notes in Github?

I would say yes.

> I'm fine with that but that might feel a bit silly/inefficient for small PR (quick fixes, typos, etc.).

Indeed, sometimes [it does](https://github.com/Copilot-Language/copilot/issues/331). It's not too bad though: those do not tend to happen a lot, and what happens is that people start attacking problems in batches (for example, they spell check complete modules when there are any typos, instead of just fixing individual typos as they find them).

> > Every issue has a milestone when it will be or was addressed.
>
> I don't think that's possible. We have plenty of issues [...]. I wouldn't put arbitrary milestones on all of those.

Sorry, I wrote it in a confusing way. I meant to say:

- Every issue that we actively work towards fixing has a milestone indicating when it will be or was addressed.

That is, if someone's actively working towards fixing it and the fix will be included in the next release, we assign it the milestone. Otherwise, no need.

The goal is that, at the end of the release, all we have to do to know what changed is go to the milestone and see all issues closed that have that milestone set.

**Comment by ivanperez-keera** [comment] 2023-07-26 15:13
> > In that case, should we backport all previous release notes in Github?
>
> I would say yes.

I just saw that some old releases were not tagged. To do this properly and not lose information, we'd have to find the commits matching the old releases, tag those commits, and then create the corresponding releases on github.

**Comment by ivanperez-keera** [comment] 2023-10-30 15:25
@arthaud I just came back to this and saw that the very first commit to the IKOS repo is tagged `v1.3`, but the versions listed in the release notes include the prior releases 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.

Just to get rid of this file and keep everything in one place, I'm going to try and find those versions, and make them available here. If I can find them, I can add them in successive commits starting from the root commit, and give them individual tags (and create the matching releases with the associated release notes).

After that, we could choose to rebase the current `master` branch on top of that last prior version v1.2. This would break the history, at the expense of keeping everything in one branch, so I'm not going to push for it.

**Comment by ivanperez-keera** [comment] 2023-11-08 19:04
> I just saw that some old releases were not tagged. To do this properly and not lose information, we'd have to find the commits matching the old releases, tag those commits, and then create the corresponding releases on github.

Actually, it's even more complicated: those releases were simply not published. The public history of IKOS restart with the first release made on github (v1.3), not with the first release in `RELEASE_NOTES` (1.0.0).

**Comment by ivanperez-keera** [comment] 2023-11-08 19:26
Given what I just said, if we remove the release notes, I suggest leaving info on old releases in the documentation directory, until old releases can be made public. I've left a sample PR here: https://github.com/NASA-SW-VnV/ikos/pull/238

It's not a perfect solution.

If, alternatively, we choose to leave this document in as it is now (including all release information), then I'd suggest:
- Updating it to include info on release 3.1.
- Renaming it to `CHANGELOG.md`.
- Documenting all changes in the document as they happen, which will be easier than going through the commits before each release trying to figure out what happened.

**Comment by arthaud** [comment] 2023-11-09 09:43
> > I just saw that some old releases were not tagged. To do this properly and not lose information, we'd have to find the commits matching the old releases, tag those commits, and then create the corresponding releases on github.
> 
> Actually, it's even more complicated: those releases were simply not published. The public history of IKOS on github starts with release v1.3, not with the first release listed in `RELEASE_NOTES`, which 1.0.0.

I think before 1.3 we were not on Github but directly on the NASA Ames website.
See for instance v1.2: https://web.archive.org/web/20170106065117/https://ti.arc.nasa.gov/opensource/ikos/
or v1.0: https://web.archive.org/web/20160614210438/http://ti.arc.nasa.gov/opensource/ikos/

**Comment by ivanperez-keera** [comment] 2023-11-28 11:56
I've made old releases available as tags. They are not in the `master` branch because we'd have to rebase everything on top of the old versions that that'd affect the 192 forks we have at the moment.

I've created matching releases on github and added the release notes for each.

As for release 3.1, we'd need to introduce the corresponding release notes. @arthaud, would you say that the following is an accurate description of that release?

IKOS version 3.1 release notes
==============================

Release date
------------

December 2022

List of changes
---------------

### LLVM frontend changes

* Upgrade LLVM from 9.0.x to 14.0.x

### Analyzer changes

* Add option to trace the invariant during analysis.
* Fix issue detecting uses of uninitialized dynamically-allocated memory.
* Allow analysis of programs without debug information.
* Support producing reports in SARIF format.
* Support producing reports in JUnit format.
* Allow running `ikos-scan` without an HTTP server, outputting JSON.
* Update use of deprecated Python function `isAlive`.
* Small refactoring changes.

### Overall changes

* Update installation instructions for Ubuntu 20.04.

**Comment by ivanperez-keera** [comment] 2023-11-29 09:28
Thanks!

**Comment by ivanperez-keera** [comment] 2023-11-29 10:27
Since all releases are now documented, the `RELEASE_NOTES.md` file can be removed altogether. I've updated my PR accordingly. I'll wait for it to build and then merge it.

**Closed** 2023-11-29 10:45 UTC
Labels: A-doc
