### ISSUE TITLE
error: could not find ikos python module in FreeBSD package

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#269] opened 2024-04-02 15:44 UTC
TROUBLESHOOTING.md says:
> The module should be under /path/to/ikos-install/lib/python*/site-packages

However, 'make install' doesn't install ```site-packages``` or any python files.

Version 3.3, 3.2
FreeBSD 14.0

**Comment by ivanperez-keera** [comment] 2024-04-10 12:32
Things changed in version 3.2.

Can you post the output of `make install`?

**Comment by yurivict** [comment] 2024-07-14 18:42
Here is the complete [log](https://freebsd.org/~yuri/ikos-3.3-build.log).

**Comment by ivanperez-keera** [comment] 2024-09-21 20:19
So, the guide is clearly wrong. That being said, some python files should be installed.

The installation process for python files changed heavily in 3.3.

I don't have (easy) access to a FreeBSD to try things. What command are you using to install things?

I see this old Makefile in ikos' freebsd package, but that doesn't seem right to me:

https://cgit.freebsd.org/ports/tree/devel/ikos/Makefile

The homebrew formula may give you further insight:

https://github.com/NASA-SW-VnV/homebrew-core/blob/d30005cf0d444acf7e07e0279e925e4b6293c8b0/Formula/ikos.rb#L37-L56

**Comment by ivanperez-keera** [comment] 2024-09-21 20:20
I'm classifying this for now as a question because it's not clear to me that anything will have to change (code wise). We may have to update the documentation to reflect where the python files are installed, though.

**Comment by ivanperez-keera** [comment] 2024-11-26 21:29
I'm not able to reproduce this. I'm moving it out of the way for now. If the issue persists, please re-open.

Also, be aware that there's been an update in #293 that fixed an issue with an outdated dependency.

**Closed by ivanperez-keera** 2024-11-26 21:29 UTC
Labels: C-question
