### ISSUE TITLE
IKOS run crash with an assertion failed

### ISSUE THREAD

**Issue by phoon0416** [NASA-SW-VnV/ikos#209] opened 2023-06-16 01:30 UTC
A simple example for this issue:
```c
#include "stdlib.h"

void* (*func_ptr)(size_t);
int main() {
	func_ptr = malloc;
	int* p = (*func_ptr)(16);

	return *p;
}
```
when analyze this program with ikos, it will cause assertion failed (file core/include/ikos/core/domain/memory/value.hpp, line 1024, ikos_assert(size.sign() == Unsigned) ), this is because when translating llvm IR to AR, the signature of function pointer func_ptr is "int* (i64)", and constant 16 is translated to signed type according to the signature of func_ptr, which will violate the assertion "ikosikos_assert(size.sign() == Unsigned)" at line 1024 in file core/include/ikos/core/domain/memory/value.hpp

**Comment by ivanperez-keera** [comment] 2023-10-30 15:32
@phoon0416 I am unable to reproduce this bug with the latest version of ikos. Could you please check if the bug still present?

Is so, could you provide more information about the OS and LLVM versions you are using? A dockerfile where this can be reproduced would be ideal but it's 100% understandable if you can't do that.

**Comment by ivanperez-keera** [comment] 2023-11-08 19:36
This is what I'm getting at the moment on a freshly built ikos:

```
[*] Compiling test.c
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
[*] Running liveness analysis
[*] Running widening hint analysis
[*] Running interprocedural value analysis
[*] Analyzing entry point 'main'
[*] Checking properties for entry point 'main'

# Time stats:
clang        : 0.419 sec
ikos-analyzer: 0.051 sec
ikos-pp      : 0.071 sec

# Summary:
Total number of checks                : 7
Total number of unreachable checks    : 0
Total number of safe checks           : 6
Total number of definite unsafe checks: 1
Total number of warnings              : 0

The program is definitely UNSAFE

# Results
test.c: In function 'main':
test.c:8:2: error: expression '*p' is uninitialized
        return *p;
        ^
```

I'm closing this issue since I'm not able to reproduce it. If you still see this problem, please re-open and add also OS and LLVM version, as well as any other information that can help us reproduce it on our side.

Thanks!

**Closed by ivanperez-keera** 2023-11-08 19:36 UTC
